# Generated by Django 6.0.3 on 2026-03-24 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50, unique=True)),
                ('status_name', models.CharField(max_length=120)),
                ('status_group', models.CharField(blank=True, max_length=120)),
                ('color_indicator', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ('status_group', 'status_name'),
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('start_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-action_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_name',)},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='no_show_probability',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='predicted_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_object',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Aidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField(blank=True, default=dict)),
                ('target_value', models.IntegerField(blank=True, null=True)),
                ('prediction_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model_version', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_data', to='salon.appointment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_workday', models.BooleanField(default=True)),
                ('breaks', models.TextField(blank=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('master', 'day_of_week', 'start_time'),
                'unique_together': {('master', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.status'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='salon.appointment')),
            ],
            options={
                'ordering': ('-payment_datetime',),
            },
        ),
        migrations.DeleteModel(
            name='MasterProfile',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
    ]
