# Generated by Django 6.0.3 on 2026-04-13 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_status_alter_service_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidata',
            options={'ordering': ('-created_at',), 'verbose_name': 'AI-данные', 'verbose_name_plural': 'AI-данные'},
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('start_datetime',), 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-action_datetime',), 'verbose_name': 'журнал действий', 'verbose_name_plural': 'журнал действий'},
        ),
        migrations.AlterModelOptions(
            name='masterschedule',
            options={'ordering': ('master', 'day_of_week', 'start_time'), 'verbose_name': 'расписание мастера', 'verbose_name_plural': 'расписания мастеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_name',), 'verbose_name': 'услуга', 'verbose_name_plural': 'услуги'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('status_group', 'status_name'), 'verbose_name': 'статус', 'verbose_name_plural': 'статусы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-payment_datetime',), 'verbose_name': 'транзакция', 'verbose_name_plural': 'транзакции'},
        ),
        migrations.AddField(
            model_name='aidata',
            name='admin_recommendation',
            field=models.TextField(blank=True, verbose_name='Рекомендация администратору'),
        ),
        migrations.AddField(
            model_name='aidata',
            name='inference_time_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Время инференса, мс'),
        ),
        migrations.AddField(
            model_name='aidata',
            name='master_risk_color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цвет риска для мастера'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_data', to='salon.appointment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='input_features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Входные признаки'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='model_version',
            field=models.CharField(max_length=100, verbose_name='Версия модели'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='prediction_probability',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вероятность неявки'),
        ),
        migrations.AlterField(
            model_name='aidata',
            name='target_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Целевое значение'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('refunded', 'Возврат')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время действия'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_object',
            field=models.CharField(default='', max_length=100, verbose_name='Объект действия'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(default='', max_length=100, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='result',
            field=models.CharField(default='', max_length=100, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='breaks',
            field=models.TextField(blank=True, verbose_name='Перерывы'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='is_workday',
            field=models.BooleanField(default=True, verbose_name='Рабочий день'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(default='', max_length=120, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Длительность, мин'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='status',
            name='color_indicator',
            field=models.CharField(blank=True, max_length=30, verbose_name='Цветовой индикатор'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код статуса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_group',
            field=models.CharField(blank=True, max_length=120, verbose_name='Группа статусов'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=120, verbose_name='Название статуса'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='salon.appointment', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус транзакции'),
        ),
    ]
