# Generated by Django 6.0.3 on 2026-04-13 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_user_middle_name_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessright',
            options={'ordering': ('role__role_name', 'operation_name'), 'verbose_name': 'право доступа', 'verbose_name_plural': 'права доступа'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('role_name',), 'verbose_name': 'роль', 'verbose_name_plural': 'роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='accessright',
            name='access_object',
            field=models.CharField(max_length=150, verbose_name='Объект доступа'),
        ),
        migrations.AlterField(
            model_name='accessright',
            name='operation_name',
            field=models.CharField(max_length=150, verbose_name='Название операции'),
        ),
        migrations.AlterField(
            model_name='accessright',
            name='permission',
            field=models.CharField(max_length=100, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='accessright',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='users.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_description',
            field=models.TextField(blank=True, verbose_name='Описание роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('blocked', 'Заблокирован')], default='active', max_length=20, verbose_name='Статус учетной записи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role', verbose_name='Роль'),
        ),
    ]
